language: node_js
node_js: 6

cache:
  directories:
  - node_modules  # NPM packages
  - bower_components  # bower packages
  - /home/travis/.nvm/versions/node/v6.5.0/lib/node_modules  # global NPM packages

install:
  - npm install -g bower polymer-cli@0.12.0
  - bower install

script: echo "Deploying!"

before_deploy: polymer build
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      tags: true
    project: hoverboard-firebase
    token:
      secure: "hLdsE9fmjZlJo8VSfeitL/4jm7OMhKC0kesJLLvS1lXo4MarXwRU86F2a7bxiRA3jrq71zI59f3d2pYfWQwyzaDxO2VOoX0IxRVxBrcRTvo8WbDIFab5x7SJQIdYxXUCsZ8/+y8VCPXBbRF2mC04BSV0rE6qLTBV6vtY5GejGunb0D+7+DLP9c8JOV6ynjLs4ENS5f0QdW7/W6OlCqU8ebd7XaXqmFNYZ36ED9OAXAYuK8iY/m2YpJy9Z0xLsXFMWRLgDhFCa0i/5Ho8G2UnCAG8+jjvuHBAD84LHpbuXTPdUNuBkNx2u810y9EENg1+ycCfarmQ5OGvrWC4fekNwRZh1BnrEhsaTm+wdI9cPfRRBNTUzhL3BkHjnYKhcszajcfXhHr1TO0mvGRY3xkLyEZVo5LBNW37mcV2JvaBdFFr8lR2YMQuvyjcIjdZN9QxqjZH4FH2cMpx5oh/XCUSaOcq17sxtOuS9qt7V3365W4CL6pPVTPSBYBpO+64XdtwocbkU4S1MpTAeyEvEeTEnzgk5nFXbmXu9mHK/irpt79Wh5t4NtVfxlvwuJxLWX+hMhU5LMASE5ogfKC42G4ZEJFIKpR11gGneiMFJ3/rPsf82PBkkLGVD4BoscN0GxhTzt+KOK/xt8QLJzTSiO8JQ8tYuxHB3Mrw7d3U0PjLz3Y="
